[package]
name = "fsm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dosio = "^0.1.2"
paste = "1.0.5"
simulink-binder = "^0.1.1"

[build-dependencies]
cc = "1.0.69"
